import type { Metadata } from "next"
import "@/styles/globals.css"

import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils"
import LandingNavbar from "@/components/navbar"
import LandingNavbarMobile from "@/components/navbar-mobile"
import { LandingFooter } from "@/components/footer"
import { Locale, i18n } from "@/i18n.config"

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map(locale => ({ lang: locale }))
}

export default function RootLayout({
  children,
  params
}: {
  children: React.ReactNode
  params: { lang: Locale }
}) {
  return (
    <html lang={params.lang}>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <LandingNavbar lang={params.lang} />
        <LandingNavbarMobile />
        {children}
        <LandingFooter />
      </body>
    </html>
  );
}
